name: Build ZMK Firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup West and Zephyr
        run: |
          pip install west
          west init -l app/
          west update
          west zephyr-export
      - name: Build firmware
        run: |
          west build -b nice_nano -- -DSHIELD=corne
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
